// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getTarget
arma::mat getTarget(arma::mat X, int varNumber, int corNumber);
RcppExport SEXP _TAS_getTarget(SEXP XSEXP, SEXP varNumberSEXP, SEXP corNumberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type varNumber(varNumberSEXP);
    Rcpp::traits::input_parameter< int >::type corNumber(corNumberSEXP);
    rcpp_result_gen = Rcpp::wrap(getTarget(X, varNumber, corNumber));
    return rcpp_result_gen;
END_RCPP
}
// getTargetSet
arma::cube getTargetSet(arma::mat X);
RcppExport SEXP _TAS_getTargetSet(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(getTargetSet(X));
    return rcpp_result_gen;
END_RCPP
}
// logML
List logML(arma::mat X, arma::mat target);
RcppExport SEXP _TAS_logML(SEXP XSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(logML(X, target));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TAS_getTarget", (DL_FUNC) &_TAS_getTarget, 3},
    {"_TAS_getTargetSet", (DL_FUNC) &_TAS_getTargetSet, 1},
    {"_TAS_logML", (DL_FUNC) &_TAS_logML, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_TAS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
